=== AbdulSamad11/AnalysisOfAlgorithms/dtd/graph.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Graph.dtd - Definición de un archivo de entrada para -->
<!-- generar una gráfica.                                 -->
<!-- Estevez Fuentes Daniel																-->
<!-- Peralta Saanta Anna Victor Miguel										-->

<!-- Una gráfica es un conjunto de vértices y aristas.    -->
<!ELEMENT graph (vertex+, edge+)>

<!-- graph tiene como atributo a direct, que indica si la -->
<!-- gráfica será dirigida (1) o no dirigida. (0)         -->
<!ATTLIST graph direct CDATA #REQUIRED>

<!-- vertex es un elemento vacio.                         -->
<!ELEMENT vertex EMPTY>

<!-- vertex tiene como atributo único la etiqueta que le  -->
<!-- asignaremos(label), la cual es única.                -->
<!ATTLIST vertex label CDATA #REQUIRED>

<!-- edge es un elemento vacio                            -->
<!ELEMENT edge EMPTY>

<!-- edge tiene como atributos: la etiqueta del vértice   -->
<!-- de origen(source), la etiqueta del vértice de destino-->
<!-- (target), y el  peso del vértice(weight).            -->
<!ATTLIST edge source CDATA #REQUIRED>
<!ATTLIST edge target CDATA #REQUIRED>
<!ATTLIST edge weight CDATA #REQUIRED>

=== AbdulSamad11/AnalysisOfAlgorithms/xml/directed.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE graph PUBLIC "-//FC//DTD red//EN" "../dtd/graph.dtd">

<graph direct="1">

    <vertex label="V0"/>
    <vertex label="V1"/>
    <vertex label="V2"/>
    <vertex label="V3"/>
    <vertex label="V4"/>
    <vertex label="V5"/>

    <edge source="V0" target="V1" weight="1"/>
    <edge source="V0" target="V4" weight="1"/>
    <edge source="V1" target="V2" weight="1"/>
    <edge source="V1" target="V3" weight="1"/>
    <edge source="V1" target="V4" weight="1"/>
    <edge source="V2" target="V3" weight="1"/>
    <edge source="V5" target="V2" weight="1"/>
    <edge source="V5" target="V4" weight="1"/>
    
</graph>

=== AbdulSamad11/AnalysisOfAlgorithms/dtd/xml/wiki.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE graph PUBLIC "-//FC//DTD red//EN" "../dtd/graph.dtd">
<!-- Peralta Santa Anna Victor Miguel -->

<graph direct="1">

    <vertex label="A"	/>
    <vertex label="B"	/>
    <vertex label="C"	/>
    <vertex label="D"	/>
    <vertex label="E"	/>
    <vertex label="F"	/>
    <vertex label="G"	/>
    
    
    <edge source="A" 	target="D " 	weight="5"/>
    <edge source="A " 	target="B " 	weight="7"/>
    <edge source="B " 	target="C " 	weight="8"/>
    <edge source="B " 	target="E " 	weight="7"/>
    <edge source="B " 	target="D " 	weight="9"/>
    <edge source="C " 	target="E "	weight="5"/>
    <edge source="E " 	target="G " 	weight="9"/>
    <edge source="E " 	target="F " 	weight="8"/>
    <edge source="E " 	target="D " 	weight="15"/>
    <edge source="G " 	target="F "	weight="11"/>
    <edge source="D " 	target="F " 	weight="6"/>
    
  
</graph>

=== AbdulSamad11/AnalysisOfAlgorithms/xml/dij.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE graph PUBLIC "-//FC//DTD red//EN" "../dtd/graph.dtd">
<!-- Peralta Santa Anna Victor Miguel -->

<graph direct="0">

    <vertex label="A"	/>
    <vertex label="B"	/>
    <vertex label="C"	/>
    <vertex label="D"	/>
    <vertex label="E"	/>
    
    <edge source="A" 	target="B" 		weight="10"/>
    <edge source="B" 	target="D" 		weight="2"/> 
    <edge source="D" 	target="E" 		weight="7"/>
    <edge source="E" 	target="D" 		weight="9"/> 
    <edge source="A" 	target="C" 		weight="3"/>
    <edge source="C" 	target="B" 		weight="4"/>
    <edge source="C" 	target="D" 		weight="8"/>
    <edge source="C" 	target="E" 		weight="2"/>
</graph>
